### ISSUE TITLE
anglosaxon with northman clothes

### ISSUE THREAD

**Issue by DarienKan** [ElTyranos/CommunityFlavorPack#100]
![anglosaxon-norse](https://user-images.githubusercontent.com/82735165/115128513-936ecb80-9fde-11eb-8c7c-ae1db7157e83.png)
Hello, 
My wife is Anglo-Saxon and her clothes do not match her culture, and so are all the women at court. The men look fine to me.

I only use this mod. I have reinstalled the Mod from github (also not from Steam before), the game is freshly installed as well. 

Thanks, 

PS: I'm new here so sorry if this isn't the right place for this post.

Edit: This happens only in my court. A well-dressed woman before I get married changes into the wrong clothes as soon as she becomes my wife.

Edit2: 
I've managed to fix it, but I honestly don't know what I'm doing: 

In the file _CFP_clothing_triggers.txt_ line 170 I have **removed**: 

portrait_northern_clothing_trigger = {
	OR = {
		scope:culture = { has_graphical_culture = northern_clothing_gfx }
		AND = {
			has_fp1_dlc_trigger = yes
			has_culture_group = culture_group:west_germanic_group
			NOT = { has_culture = culture:english }
		}
	}

**Comment by ElTyranos** [comment]
This is a feature as Northern Lords DLC made "north" clothing almost not used but in ireland. They will transition to western clothing when becoming english, leaving their wool clothes for a closer thing to high medieval fashion.

**Comment by DarienKan** [comment]
In Vanilla doesn't happen, is not a feature NL DLC, but, ok, nervermind.

**Comment by ElTyranos** [comment]
Should be fixed by now.
