### ISSUE TITLE
Cuman women wear circlets now by default

### ISSUE THREAD

**Issue by voy178** [ElTyranos/CommunityFlavorPack#107]
![20210424235717_1](https://user-images.githubusercontent.com/44323473/115973928-f0c3c900-a558-11eb-9253-a2a0bdcef5ee.jpg)

Did you accidentally unlock the European circlets for the steppe cultures or is this intentional?

**Comment by ElTyranos** [comment]
Sounds like a bug

**Comment by ElTyranos** [comment]
fixed
