### ISSUE TITLE
Men of gods: Cardinals

### ISSUE THREAD

**Issue by eccekevin** [ElTyranos/CommunityFlavorPack#109]
Brief history and disclaimer: The history of clergy vestments is very fuzzy. Cardinals have existed since the first century, but they were normal priests and didn’t become prominent until after 1059. Until then, their attire was probably unrecognizable from that of a bishop, alas the emphasis on red seems to always have been present (the pope’s colors were red and white since before the year 1000). They really got their own dress code in the following centuries, culminating in 1245 at the [council of Lyon](https://en.wikipedia.org/wiki/First_Council_of_Lyon) , when pope Innocent IV invented the [galero](https://en.wikipedia.org/wiki/Galero) the very recognizable hat that symbolizes cardinals to this very day. The galero (always red) initially was accompanied by fancy robes that were often but not always not always red  although eventually red won out. In the end, a very special robe and galero combination was created, and lasted for many centuries. 

Starting with the renaissance, the cardinals looked different ([like this](https://www.tvequals.com/wp-content/uploads/2011/04/THE-BORGIAS-Showtime-Premiere-The-Poisoned-Chalice-The-Assassin-16.jpg)), but here I’m providing pictures for medieval ones: 

<img width="855" alt="Screen Shot 2021-05-31 at 11 46 36 PM" src="https://user-images.githubusercontent.com/84947325/120278736-80504c00-c26a-11eb-83a3-7e175233ed97.png">
<img width="851" alt="Screen Shot 2021-05-31 at 11 46 41 PM" src="https://user-images.githubusercontent.com/84947325/120278739-821a0f80-c26a-11eb-83b3-07a2365933ca.png">
<img width="847" alt="Screen Shot 2021-05-31 at 11 46 46 PM" src="https://user-images.githubusercontent.com/84947325/120278745-83e3d300-c26a-11eb-9594-a99518c19232.png">
<img width="847" alt="Screen Shot 2021-05-31 at 11 46 52 PM" src="https://user-images.githubusercontent.com/84947325/120278753-86462d00-c26a-11eb-8b42-575ac5fb3544.png">

Here are good reconstructions from shows

From 'Borgia'
![image](https://user-images.githubusercontent.com/84947325/120277619-21d69e00-c269-11eb-8ba6-171789a336da.png)
![image](https://user-images.githubusercontent.com/84947325/120277809-606c5880-c269-11eb-9200-c47706f650f6.png)

From The Concalve (2006)
![image](https://user-images.githubusercontent.com/84947325/120277307-bc82ad00-c268-11eb-89eb-ef8e336e6444.png)
![image](https://user-images.githubusercontent.com/84947325/120277323-c1dff780-c268-11eb-83f8-398503798305.png)
![image](https://user-images.githubusercontent.com/84947325/120277332-c5737e80-c268-11eb-9a0f-6e3a915692ab.png)
![image](https://user-images.githubusercontent.com/84947325/120277341-c9070580-c268-11eb-8398-27678e12d366.png)
![image](https://user-images.githubusercontent.com/84947325/120277350-cc9a8c80-c268-11eb-9417-c7ab0ea313e0.png)

**Comment by ElTyranos** [comment]
Done.
