### ISSUE TITLE
Byzantine helmets 

### ISSUE THREAD

**Issue by Reaper2055** [ElTyranos/CommunityFlavorPack#11]
#suggestion
Could you add some byzantine helmets, I'd really like to see Byzantine kettle helmets (as they invented them and wore them in this period) some older more burgh castle style helmets would also look nice, although may be a little outdated at the current start dates. I also really like the asthetics of the byzantine chain mask used with most types of their helmets.

![unnamed](https://user-images.githubusercontent.com/71154502/92973553-548efb00-f47c-11ea-86a3-eb7f02ed8964.jpg)
byzantine kettle helmet
![kettle with chain](https://user-images.githubusercontent.com/71154502/92973959-0f1efd80-f47d-11ea-82b2-4e7430472dbd.png)
Byzantine Kettle helmet with chain mask
![chainmail](https://user-images.githubusercontent.com/71154502/92974061-442b5000-f47d-11ea-9c27-04500a8a4f5f.jpg)
a riveted helmet with chainmail mask based on a find in bulgaria (side note the website this image is on also has some interesting details http://www.levantia.com.au/byzarmour.html)
![chainmail 2](https://user-images.githubusercontent.com/71154502/92974130-7341c180-f47d-11ea-8df0-02628011f3e2.jpg)
Another helmet similar to the previous one

There is a lot of evidence of byzantine soldiers using the "Caucasian’ type of helmet, which is already in the game as byzantine helmet but i don't like the one in the game presume that a new type will be added when you add the cuman mask my additional suggestion would be to add a version without the mask, as well as one with a chain mail mask like with the other byzantine helmets (they sure seemed to enjoy wearing those chainmail masks) this one is heavily associated with the cataphracts
![Cataphract](https://user-images.githubusercontent.com/71154502/92975869-29f37100-f481-11ea-82c0-2165a770bc3c.jpg)
![cataphract 2](https://user-images.githubusercontent.com/71154502/92975877-2cee6180-f481-11ea-8246-2e7d79cc688a.jpg)

![knight-s-helmet-old-chain-mail-protection-battle-made-metal-knightly-armor-43173028](https://user-images.githubusercontent.com/71154502/92976020-7b9bfb80-f481-11ea-854f-3701d0b0f96a.jpg)
This one seems to be a varangian helmet (again with the chainmail mask)

**Comment by ElTyranos** [comment]
Done the 10th century Roman one from bulgaria, will do more later so the card remains opened.

**Comment by DemetrRUS** [comment]
![image](https://user-images.githubusercontent.com/71565949/93914029-9b97ae80-fd0e-11ea-94f1-bf717d9057ea.png)
This is a "steeply-domed" helmet. It was produced in Russia, Volga Bulgaria, Bulgaria, the Caucasus, and West Asia.

**Comment by ElTyranos** [comment]
Transferred to suggestion box
