### ISSUE TITLE
Slovianskan Poles wearing sugarloaf helms in 877

### ISSUE THREAD

**Issue by Belaidev** [ElTyranos/CommunityFlavorPack#12]
![image](https://user-images.githubusercontent.com/65010410/93007081-63d08000-f532-11ea-8aae-8565b37f78e3.png)
![image](https://user-images.githubusercontent.com/65010410/93007085-6c28bb00-f532-11ea-8e98-9d97b2d4a947.png)

**Comment by ElTyranos** [comment]
Fixed as good as vanilla setup can offer  by removing it from `western` and leaving it in `hre` (Holy Roman Empire), this way, it should appear later into the game.
