### ISSUE TITLE
Game is crashing on startup

### ISSUE THREAD

**Issue by hal0dude7** [ElTyranos/CommunityFlavorPack#121]
Hello, as the title says I just discovered that for some odd reason, my game crashes when the mod is enabled, tested it with just CFP enabled and it still crashes. It also sometimes causes weird side effects like my browser freezing or steam looking all wonky, screenshot attached for reference. 
![Desktop Screenshot 2022 02 15 - 19 39 02 34](https://user-images.githubusercontent.com/99751095/154107418-c0662315-b72a-49bb-8705-7faec440f71d.png)

**Comment by ElTyranos** [comment]
Hello,

https://wiki.communityflavorpack.com/troubleshooting/force-reinstall

Try to do option 2, it will force redownload everything. I suppose you have a corrupted 3D file that leads to a CTD.

Good luck!
