### ISSUE TITLE
Iberian Court scene defaults to Muslim Iberian court scene

### ISSUE THREAD

**Issue by donsuave** [ElTyranos/CommunityFlavorPack#127]
When playing in Iberia as a religion other than Christian or Muslim, the court scene seems to default to the Andalusian court, regardless of culture of the ruler or capital county culture. Is there a way to get the “Christian” Iberian court scene when playing as a religion that is not Christian or Muslim in  Iberia?

**Comment by ElTyranos** [comment]
Please post error.log and database.log

**Comment by donsuave** [comment]
[error.log](https://github.com/ElTyranos/CommunityFlavorPack/files/8903509/error.log)
[database_conflicts.log](https://github.com/ElTyranos/CommunityFlavorPack/files/8903523/database_conflicts.log)

I've been able to partially solve the issue with this alteration in CFP_scenes_culture:

Original:

iberian = {
	trigger = {
		exists = capital_county
		capital_county.culture = {
			has_graphical_iberian_culture_group_trigger  = yes
			prev.religion = religion:christianity_religion
		}
	}
}

andalusian = {
	trigger = {
		exists = capital_county
		capital_county.culture = {
			has_graphical_iberian_culture_group_trigger  = yes
			prev.religion = religion:islam_religion
		}
	}
}
New:

iberian = {
	trigger = {
		exists = capital_county
		capital_county.culture = {
			has_graphical_iberian_culture_group_trigger  = yes
			NOT = {prev.religion = religion:islam_religion}
		}
	}
}

andalusian = {
	trigger = {
		exists = capital_county
		capital_county.culture = {
			has_graphical_iberian_culture_group_trigger  = yes
			prev.religion = religion:islam_religion
		}
	}
}

This changes it so any Iberian culture that isn't Muslim will have the "Christian Iberian" royal court, while any Muslim Iberian culture will have the "Andalusian" royal court

**Comment by ElTyranos** [comment]
Good idea, I will think about it.
Take care, The Catholic Trinity is not updated yet.
