### ISSUE TITLE
15th Century Plate Helms

### ISSUE THREAD

**Issue by heuristicanalysis** [ElTyranos/CommunityFlavorPack#13]
Suggestion for addition of sallets and armet helmets for the late-medieval period. Obviously, not all of these would need to be added, but some late-century helmets would be awesome to see on commanders, etc.

Examples:

Greenwich armour (Henry VIII's armour):
https://en.wikipedia.org/wiki/Greenwich_armour#/media/File:Henry_VIII's_expensive_armour.jpg 

Sallet:

German - 
![image](https://user-images.githubusercontent.com/71201349/93009031-2108b980-f5bf-11ea-8cf6-e389b79127f0.png)

https://images-wixmp-ed30a86b8c4ca887773594c2.wixmp.com/f/c11ac74b-c2f4-4958-b376-fd55c728a48b/darsswi-547eff60-04b2-47d1-8620-e6e9e29fde4c.jpg/v1/fill/w_1024,h_424,q_75,strp/germanic_non_visored_sallets__late_15th_century__by_robbiemcsweeney-darsswi.jpg?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJ1cm46YXBwOjdlMGQxODg5ODIyNjQzNzNhNWYwZDQxNWVhMGQyNmUwIiwic3ViIjoidXJuOmFwcDo3ZTBkMTg4OTgyMjY0MzczYTVmMGQ0MTVlYTBkMjZlMCIsImF1ZCI6WyJ1cm46c2VydmljZTppbWFnZS5vcGVyYXRpb25zIl0sIm9iaiI6W1t7InBhdGgiOiIvZi9jMTFhYzc0Yi1jMmY0LTQ5NTgtYjM3Ni1mZDU1YzcyOGE0OGIvZGFyc3N3aS01NDdlZmY2MC0wNGIyLTQ3ZDEtODYyMC1lNmU5ZTI5ZmRlNGMuanBnIiwid2lkdGgiOiI8PTEwMjQiLCJoZWlnaHQiOiI8PTQyNCJ9XV19.DCxbBrE4i3LBKWB96lkJ5ciCap8fwBAioM71DMcLOOs

Italian -

http://www.therionarms.com/reenact/therionarms_c1284.jpg 

Armets:

https://c1.staticflickr.com/3/2198/2332647355_e9551c7601_b.jpg

http://www.ageofarmour.com/images/armet04side.jpg

**Comment by TJBMinecraft** [comment]
i do hope you realise that The greenwich armour is not 15th century, but instead 16th century
