### ISSUE TITLE
Coppergate Helmet

### ISSUE THREAD

**Issue by ElTyranos** [ElTyranos/CommunityFlavorPack#14]
![image](https://user-images.githubusercontent.com/6755711/93030356-aec9c080-f622-11ea-8431-bacab0e81e36.png)
Anglo Saxons

**Comment by GSrategos** [comment]
Looks amazing! Would definitely like to see int in-game!

**Comment by ElTyranos** [comment]
Derivatives can be used in proto-iberian cultures as per https://github.com/ElTyranos/CommunityFlavorPack/issues/18

**Comment by ElTyranos** [comment]
Transferred to suggestion box
