### ISSUE TITLE
Kipchak mask

### ISSUE THREAD

**Issue by ElTyranos** [ElTyranos/CommunityFlavorPack#15]
![image](https://user-images.githubusercontent.com/6755711/93030440-74145800-f623-11ea-9483-b35a10db6a55.png)

![image](https://user-images.githubusercontent.com/6755711/93030456-88f0eb80-f623-11ea-8b88-62bc2332f1cd.png)

`so many people mistake Cumans/Kipchak for Mongols like in Bannerlord with the Khuzaits and after studying Cumans and Kipchaks more so Cumans it always irks me when it's done incorrectly like proper research isn't hard haha`

**Comment by SlavaStalin7799** [comment]
Its a good slav helmet too. Russian Boyars and heavy infantry. 
![3 (1)](https://user-images.githubusercontent.com/71362337/93286486-61c22780-f7a5-11ea-8ff0-83b79d57916b.jpg)

**Comment by edward4536** [comment]
@ElTyranos great idea! you can use the helm with different mask features for their corresponding cultures (e.g.slavs used different face features as say kipchaks, the beard was their trademark though). The base helmet is similar, however different face plates can make cultures differentiate.
![slavic-cone-helm-helmet-armor-with-face-mask-visor](https://user-images.githubusercontent.com/50803571/93802748-2bbcf180-fc44-11ea-8b55-ba44058f6124.jpg)

![slavic-cone-helm-helmet-armor-with-face-mask-visor-1](https://user-images.githubusercontent.com/50803571/93802765-2f507880-fc44-11ea-8b41-06112a51a70d.jpg)

![xg3ye1cj92d51](https://user-images.githubusercontent.com/50803571/93802755-2d86b500-fc44-11ea-89e1-0d8a76512f13.jpg)

**Comment by ElTyranos** [comment]
Transferred to suggestion box
