### ISSUE TITLE
 Iberian christian cultures helmets

### ISSUE THREAD

**Issue by zoosant** [ElTyranos/CommunityFlavorPack#18]
#suggestion
Could you add some iberian helmets like the morrion, to give more immersion to the reconquista? Ok, I know that they are late to the fifteen century but I would like to see more variety in Iberian culture, at least on castillian or portuguese culture. (I forgotten that germans  wear those helmets, so they could also use it)

a decorated morrion to hight nobles:
![image](https://user-images.githubusercontent.com/71384968/93334411-33842c80-f825-11ea-9ba0-ad694ea1d897.png)

or a common morrrion
![image](https://user-images.githubusercontent.com/71384968/93334763-bd33fa00-f825-11ea-8228-ba4277e92f7d.png)

and also some helmets to the visigothic and suebi culture like these:
![image](https://user-images.githubusercontent.com/71384968/93335287-7a265680-f826-11ea-909e-c139a5ed544f.png)

![image](https://user-images.githubusercontent.com/71384968/93335413-b659b700-f826-11ea-9aaa-b5ee93fe521c.png)

or the suggested coppergate helmet

**Comment by ElTyranos** [comment]
Morrion is definitely too late, especially as there is no era-unlock system, I don't want to go that  late as it would spawn right from 867... 

Otherwise the  other two seem fine. Thanks for the references.

**Comment by zoosant** [comment]
No problem 😆

**Comment by Willemoak** [comment]
I have to disagree with these suggestions. Not only the morrion is way too late, but the rest of the suggestions would look out of place in both the early and late starting dates.

This is what Iberian knights looked like between the 1100 and the 1300's
[https://preolivodecazorla.com/wp-content/uploads/2016/03/spanish-horse-middle-ages.jpg](url)

[https://www.ancient.eu/img/c/p/1200x627/9300.jpg?v=1600453807](url)

[https://upload.wikimedia.org/wikipedia/commons/e/e0/Pintures_murals_de_la_conquesta_de_Mallorca-2.jpg](url)

Notice the round cerveillere, sometimes simple, sometimes trimmed (always heraldic), the heavy leather perpunctus over the heraldic tabard, and the absence of nasal or conic helms of any kind.

**Comment by zoosant** [comment]
Ok, but the Suebian culture, which is in the game, could use some of the
helmets  , like the anglo-saxon with the coppergate helmet.

**Comment by ElTyranos** [comment]
sorted and planned
