### ISSUE TITLE
Bascinet Variations

### ISSUE THREAD

**Issue by bubonic-supersonic** [ElTyranos/CommunityFlavorPack#23]
#suggestion

So the first three suggestions are all variations of the bascinet helmet.
The first one is the houndskull bascinet.
![pemdd675zy451](https://user-images.githubusercontent.com/71673344/93827362-ba267880-fc2e-11ea-88e5-93bb5f797b54.png)
![medieval-western-knights-armor-kit-the-kings-guard](https://user-images.githubusercontent.com/71673344/93827371-bf83c300-fc2e-11ea-9dc4-85ba7d2b1e77.jpg)

The next is the Klappvisor.
![German_Klappvisor_1__73282 1528634640](https://user-images.githubusercontent.com/71673344/93827414-d1656600-fc2e-11ea-8cbd-a40c325926ae.jpg)
![mib-1310-6506_03](https://user-images.githubusercontent.com/71673344/93827419-d4f8ed00-fc2e-11ea-9168-a64bd2036fc0.JPG)

And finally, a bascinet with a nose guard. Although to be fair, this one looks somewhat similar to the byzantine helmet with mail you've already added.
![b03b201e1be8aae6dc3dcf9ab2378350](https://user-images.githubusercontent.com/71673344/93827496-fce85080-fc2e-11ea-9460-0c0bd8c48c28.jpg)

Keep up the good work!

**Comment by ElTyranos** [comment]
Transferred to suggestion box
