### ISSUE TITLE
Norman Phrygian Helmet

### ISSUE THREAD

**Issue by ElTyranos** [ElTyranos/CommunityFlavorPack#27]
- [x] Check if the norman sicilian culture exists.

![image](https://user-images.githubusercontent.com/6755711/94589245-554dcc80-0285-11eb-8521-6908a1fc454f.png)

**Comment by GStrategos** [comment]
A very nice addition!

**Comment by ElTyranos** [comment]
There's no subculture for sicilian normans. Sob.

**Comment by ElTyranos** [comment]
Planned
