### ISSUE TITLE
crowns for Castillian culture

### ISSUE THREAD

**Issue by zoosant** [ElTyranos/CommunityFlavorPack#35]
**king sancho IV crown**

![image](https://user-images.githubusercontent.com/71384968/95449700-65d90380-0965-11eb-82ca-c5c689b57e10.png)

queen Isabel I"the catholic"crown, 
![image](https://user-images.githubusercontent.com/71384968/95450660-e2b8ad00-0966-11eb-964e-1dda6fde561b.png)

**Comment by ElTyranos** [comment]
planned in 2.2
