### ISSUE TITLE
Iberian (1100-1250's) wargear, bonnets and crowns

### ISSUE THREAD

**Issue by Willemoak** [ElTyranos/CommunityFlavorPack#36]
Hi there. I'm leaving here my suggestions and reference images for what I believe would be the most accurate and least intrusive Iberian gear, some of it also applicable to Italians and Occitans, keeping anachronism to a minimum (i.e. no late Medieval items, and no one-offs way outside the scope of the 1066 start, which is the most representative start of the game)

First off, the iconic flat top bonets. Judging from the illuminations in works like Las Cantigas, it was quite popular among the nobility, embroidered with gold or silver thread. Alfonso X owned a very special one with lions and castles.

![](https://2.bp.blogspot.com/-7OiqD_e6JOI/VaYxgWdKeYI/AAAAAAAAAXU/RxMKrc9Kjrc/s1600/sombrero.jpg)

![](https://i.pinimg.com/originals/04/24/cf/0424cfdc790ff5d46336f249e23cf27f.png)

This 19th Century picture has a lot of well-researched flat top bonnets:
https://upload.wikimedia.org/wikipedia/commons/6/69/Campanahuesca.jpg

And here's examples of other sorts of headwear typical of the High Middle Ages:
http://aulamedievalindumentaria.blogspot.com/2015/04/sobretodo-2.html

Then, Romanesque crowns:

https://www.bcncatfilmcommission.com/sites/default/files/styles/film-gallery/public/films/Foto%202_29.jpg?itok=MvvZYT9U

![](https://i0.wp.com/www.xn--espaaescultura-tnb.es/export/sites/cultura/multimedia/galerias/obras_excelencia/diocesano_palencia_Virgen_de_Dehesa_Bravac_002147.jpg_1306973099.jpg)

https://2.bp.blogspot.com/-MnCTZzgXQAI/V9U_cjh1dQI/AAAAAAAAeoI/iwBys1QsNIw12ecTMVb6wfR7kbSp6fzygCLcB/s1600/IMG_4422.JPG

And the wargear I already posted before:

![](https://www.elnacional.cat/uploads/s1/40/71/59/1/campament-de-jaume-i-font-mnac.png)

![](https://docplayer.es/docs-images/64/52148440/images/55-0.jpg)

![](https://statics.ccma.cat/multimedia/jpg/5/4/1485354923645.jpg)

**Comment by ElTyranos** [comment]
![image](https://user-images.githubusercontent.com/6755711/97116154-9954b580-16fb-11eb-9d28-a8d2555b13d8.png)
![image](https://user-images.githubusercontent.com/6755711/97116156-9ce83c80-16fb-11eb-8328-916d0e2a8569.png)

**Comment by Willemoak** [comment]
Nice, Al-Mansur's pack of helmets from our old M&B days xD - I worked on Europe 1200 there for years, I've got fond memories of those times. 

Here's a recreation of a 1200-1250 Iberian nobleman, he looks like he rose from the walls of the Conquest of Mallorca murals:
https://i.pinimg.com/originals/f4/d6/78/f4d67821b2cbbee01fa3229fbcad6c85.jpg

**Comment by ElTyranos** [comment]
planned in 2.2
