### ISSUE TITLE
Beards clipping threw Slavic helmets with chainmail covering

### ISSUE THREAD

**Issue by voy178** [ElTyranos/CommunityFlavorPack#48]
![20201025164622_1](https://user-images.githubusercontent.com/44323473/97111926-d744e000-16e1-11eb-8b14-ae14685f8dbb.jpg)

**Comment by ElTyranos** [comment]
Mmh I'd have to look if that is possible to add new blend shapes categories for aventails since the game is not planned for those. Most of beards should fit tho thanks to the "hood" blend shape.

Won't be fixed before a while I suppose, unless I disable all beards display for this helmet.
