### ISSUE TITLE
Byzantine/Slavic Armor/Helmets/Accessories

### ISSUE THREAD

**Issue by prwoyt** [ElTyranos/CommunityFlavorPack#55]
I know you guys have already made a Byzantine update, but I think there's a lot more you could add, and because of this I think it'd just be better to create another update based around Byzantium and the parts of Eastern Europe where Orthodoxy would spread.

General Byzantine/Kievan-
![image](https://user-images.githubusercontent.com/59941759/99484482-7f8b4480-292e-11eb-8400-0cbc948c4935.png)
^From this image you could add the scalemail armor, this way some Byzantine characters could use it so that not everyone's wearing the same thing, and this armor could help separate the armor of the Slavic nations and the Viking nations.
Also in this image there's a smaller round shield, which I think could be a cool accessory.
The cape that wraps around the front a bit would also be a nice addition.
![image](https://user-images.githubusercontent.com/59941759/99484896-5323f800-292f-11eb-9dac-d34a8a9c749c.png)
^Byzantine Chainmail
![image](https://user-images.githubusercontent.com/59941759/99484987-78b10180-292f-11eb-84c4-be6a39d8412e.png)
^Byzantine Gambeson

Varangian-
![image](https://user-images.githubusercontent.com/59941759/99485097-c594d800-292f-11eb-8ccb-a45d0d19c2f1.png)
![image](https://user-images.githubusercontent.com/59941759/99485226-08ef4680-2930-11eb-91e9-d2f69cd643a8.png)
^From here there's the helmet which would be a cool edition, as well as the Varangian lamellar. The "Byzantine Chainmail" I mentioned earlier is also in the first picture on the left.

Byzantine Cataphract Armor-
![image](https://user-images.githubusercontent.com/59941759/99485377-579ce080-2930-11eb-97e1-6c14c02d4ca4.png)
^In this image there's this sort of plate mail featured on the armos with lamellar, possibly another cool edition. This armor could be used by Byzantine champions.

Kievan/Slavic Lamellar-
![image](https://user-images.githubusercontent.com/59941759/99485595-ba8e7780-2930-11eb-8d32-1502961cc4a4.png)
^In here there's just some more armor that could be used to differentiate Slavs and Vikings, or specifically for Gardariki and other nations in the area. Just lamellar with chain. The cape I mentioned earier also appears in this picture.

**Comment by ElTyranos** [comment]
Transferred to suggestion box
