### ISSUE TITLE
Full Nude Orthodox Rulers xdd

### ISSUE THREAD

**Issue by Ch1llex** [ElTyranos/CommunityFlavorPack#59]
This mod makes my orthodox rulers and vassals go full nude xd <3 Fix this <3

**Comment by ElTyranos** [comment]
![image](https://user-images.githubusercontent.com/6755711/100515397-29af6b80-317c-11eb-8fcb-5f2ee6051068.png)

I can't reproduce. Check your modset, you likely have an incompatibility.
