### ISSUE TITLE
Crown of Stefan Dečanski 

### ISSUE THREAD

**Issue by AnthonyAT33** [ElTyranos/CommunityFlavorPack#62]
![kruna05](https://user-images.githubusercontent.com/28011460/102729169-e33ece00-432f-11eb-800e-0d0a908ee242.jpg)
![kruna06](https://user-images.githubusercontent.com/28011460/102729172-e46ffb00-432f-11eb-9efc-ae242e924d51.jpg)
![kruna01](https://user-images.githubusercontent.com/28011460/102729174-e46ffb00-432f-11eb-9798-57d1918ff5d2.jpg)
![kruna02](https://user-images.githubusercontent.com/28011460/102729175-e46ffb00-432f-11eb-8478-32f9c4a3c53f.png)
![kruna03](https://user-images.githubusercontent.com/28011460/102729178-e8038200-432f-11eb-9ceb-370050a9c54b.png)
![kruna04](https://user-images.githubusercontent.com/28011460/102729179-e934af00-432f-11eb-9dfb-eb0c872cdd67.jpg)

![Sides](https://user-images.githubusercontent.com/28011460/102729939-0454ee00-4333-11eb-8119-e0df5525029b.png)

Fresco depicting St. Stefan Dečanski
![stefandeckanski](https://user-images.githubusercontent.com/28011460/102729180-e934af00-432f-11eb-9084-6c5c3d0f6d7e.jpg)

**Comment by ElTyranos** [comment]
Transferred to suggestion box.
