### ISSUE TITLE
Two items of 'Abbasid-era Muslim costume

### ISSUE THREAD

**Issue by hentuspants** [ElTyranos/CommunityFlavorPack#67]
**Taylasan**

One thing that I think is very much needed is the taylasan, a trapezoid piece of (usually pale) material worn over the shoulders and hanging down from them, and often long enough to cover the turban (sometimes being pinned in place). It was the special garb marking out in particular the qadi and faqih - judges and law officials - although not forbidden from the use of common people (Tabari mentions one worn by a clerk in the 'Abbasid caliphal palace). 

It continued to be used by the learned 'ulama' class as a marker of distinction throughout the Islamic period. This would be fitting for a special item of dress worn by the CK3 Muslim 'court chaplain' / 'realm priest' regardless of affiliation.

![](https://cdn.discordapp.com/attachments/754383743422300221/786586644907294720/Qadiwithlitigants.jpg)

![](https://cdn.discordapp.com/attachments/754383743422300221/786586650624655390/Qadiwithlitigants2.jpg)

You can see two ways of wearing the taylasan from the images above - one, around the shoulders with the turban uncovered, the other with it draped over the turban, and possibly secured in place.

**Qalansuwa Tawila**

Iconic in the minds of 'Abbasid scholars, and yet very rarely depicted, the qalansuwa tawila (very roughly translated as "tall hat") was an essential piece of costume in the 'Abbasid court in the 9th and 10th centuries. Although starting at a modest size, this hat grew to an incredible size, mocked by contemporaries as inversely proportional to the political power of the bearers in the rapidly decaying Caliphate. It was eventually discarded in favour of other styles of headwear.

The taller qalansuwa hats kept their structure by means of an internal framework of wood or reeds (think in similar terms to the 'gat' hat depicted in Korean period dramas). Over this scaffolding was a layer of fine and expensive material, such as silk, sometimes with sewn patterns or quilting. A turban or piece of material may be worn around the base, or the hat worn without further ornamentation.

The below image depicts two illustrations of qalansuwa tawila from the Osprey Military series in their initial, very much shorter stage. The last image, an illustration from a 1009 CE book on constellations in which the constellation Cepheus wears a qalansuwa tawila, is more appropriate for the latter stage (but they could get higher than this).

![Taller!](https://user-images.githubusercontent.com/76923451/103890487-14651f80-50e0-11eb-940f-d80b3e8199c8.jpg)

For CK3, I would recommend that both heights be represented (perhaps with the latter also surrounded by cloth), as they are emblematic of the early Islamic period (although a thing of the past by the 1066 bookmark). The latter should be reserved for emirs and other powerful men, and a black version - i.e. without any colour variation - be reserved for the Caliph and his council along with black robes, as this was the hue favoured by those loyal to the 'Abbasids even well after the decline of their territorial empire.

NB. It is important to differentiate this from other qalanis worn by other orders of society, such as the more cap-like hat worn by the ghulam soldier on the right in the following Osprey illustration:

![Ghilman](https://user-images.githubusercontent.com/76923451/103893513-56449480-50e5-11eb-9915-d1c1be69827f.png)

I have other suggestions, but I'm sure this will do for now. :)

**Comment by ElTyranos** [comment]
Done in iranian and mena packs
