### ISSUE TITLE
late roman clothes for roman culture

### ISSUE THREAD

**Issue by zoosant** [ElTyranos/CommunityFlavorPack#69]
I know that the Roman culture is outside the temporal limits of the game, but I think it needs something that identifies it from the Greek culture apart from the laurel wreath
toga:
![image](https://user-images.githubusercontent.com/71384968/104818224-8d721e80-5826-11eb-8692-042f76629e68.png)
manicata:
![image](https://user-images.githubusercontent.com/71384968/104818368-6e27c100-5827-11eb-9484-334398203c14.png)

**Comment by ElTyranos** [comment]
Transferred to suggestion box
