### ISSUE TITLE
Early 14th century Mamluk Sultan's helmet (for Late MENA pack)

### ISSUE THREAD

**Issue by ShahAfshar** [ElTyranos/CommunityFlavorPack#71]
**Reference** : https://www.artandhistory.museum/fr/masterpieces/casque-mamelouk
https://i.redd.it/fj4auk5fq9r01.jpg

14th century Mamluk helmet that belonged to the Sultan Al-Nasir Muhammad (1285-1341). Made from Iron and Gold, in Egypt or Syria. High resolutions pictures available on the links above.

"A gilt band runs encircles the helmet, with an inscription in Thuluth calligraphy against a background of arabesques listing the name and title of Sultan al-Nasir Muhammad ibn Qalawun, who reigned from 1293 until 1341. The nose guard could slide down. Feathers were originally affixed on both sides and the top of the helmet."

In my opinion, it could be used in the game as a war helmet for Kings+ level in Egypt, Syria and Mesopotamia (Egyptian and Mashriki cultures).

![image](https://user-images.githubusercontent.com/77591085/104857109-92ae9680-5916-11eb-8dbf-09b44b1f92ab.png)

![image](https://user-images.githubusercontent.com/77591085/104857324-ebcafa00-5917-11eb-9b2f-cddd15ed82c9.png)

In case you want to add the original feathers, I guess this could be used as inspirations (I saw one of them is already in the roadmap)

![image](https://user-images.githubusercontent.com/77591085/104857560-a7405e00-5919-11eb-9631-7a9a1ec0dc87.png)

![image](https://user-images.githubusercontent.com/77591085/104857511-4a44a800-5919-11eb-92c5-331b0e945383.png)

**Comment by ElTyranos** [comment]
Done in MENA Pack !
