### ISSUE TITLE
Plate armour helmet (open and closed) is used casually for non-martial characters at peace

### ISSUE THREAD

**Issue by voy178** [ElTyranos/CommunityFlavorPack#72]
To a rather comical effect, I might add.
![20210118004124_1](https://user-images.githubusercontent.com/44323473/104859537-6569e480-5926-11eb-9b2d-03c881ab2993.jpg)

**Comment by ElTyranos** [comment]
This is a vanilla bug

https://forum.paradoxplaza.com/forum/threads/ck-iii-lots-of-characters-use-war-headgear-without-armor.1448012/

**Comment by voy178** [comment]
I distinctly remember you fixing it a few updates ago quite successfully. Was it too much work?

**Comment by ElTyranos** [comment]
It was another issue caused by my own code. Here it's a paradox mistake, I have not even checked what they did wrong.

**Comment by ElTyranos** [comment]
Fixed my way until PDX fix their code.
