### ISSUE TITLE
Suggestion: Late Medieval (Turkic/Iranian/Indian) Islamic Armors

### ISSUE THREAD

**Issue by nicobasileus** [ElTyranos/CommunityFlavorPack#78]
As an Islamic counterpart to the late-game brigandine and Churburg plate armors, I suggest "mirror armor" for (at least) Turkic, Iranian, and Indian Muslim characters:

![73303d79c85db69b21f0e8114434fc6a](https://user-images.githubusercontent.com/75342984/105643838-23213580-5e47-11eb-919a-f9f61b7d5fb3.jpg)
![dd7fe406bc5f9010a542295300ca1267](https://user-images.githubusercontent.com/75342984/105643839-261c2600-5e47-11eb-87d3-5f80f90b27a3.jpg)
![TopkapiTurkish15thC](https://user-images.githubusercontent.com/75342984/105643840-274d5300-5e47-11eb-8a67-b4fcddb56a3a.jpg)

The armor originated in 13th century Central Asia and eventually found itself being used throughout the entire Islamic world by the 14th Century from the Ottoman Turks and Egyptian Mamelukes in the west to the Persians and Indo-Persians (especially the Mughals) further east. 
![1200px-Chahar-Aine_or_char-aina_(four_mirror_armour)_and_chainmail_armor _Akbar's_Personal_Armor,](https://user-images.githubusercontent.com/75342984/105644021-48627380-5e48-11eb-8222-36fb52a2b6ea.jpg)

Above is the armor worn by the Mughal emperor Akbar. Although it's from the 17th century, his Iranian-style armor more or less remained the same appearance or "framework" as older Iranian mirror armor before it.

![Antique_Indian_char-aina_(chahar-aina),_kulah_khud_and_madu](https://user-images.githubusercontent.com/75342984/105643985-0d604000-5e48-11eb-9f3b-1b2980398d29.jpg)

^Another example of Iranian mirror armor, also featuring an ornate Khud (helmet) on top of chainmail.

References:
https://weaponsandwarfare.com/2015/11/07/1400-1590-ottoman-weapons-ii/ (Musée de l’Armée, Paris)

https://commons.wikimedia.org/wiki/File:Chahar-Aine_or_char-aina_(four_mirror_armour)_and_chainmail_armor._Akbar's_Personal_Armor,.jpg (Prince of Wales Museum, Mumbai)

Topkapi Museum, Istanbul

*Pictures are not mine*

**Comment by ElTyranos** [comment]
Transferred to suggestion box
