### ISSUE TITLE
Andalusian Great Helm

### ISSUE THREAD

**Issue by zoosant** [ElTyranos/CommunityFlavorPack#80]
![image](https://user-images.githubusercontent.com/71384968/107143216-1a932980-6934-11eb-8ba7-0be9914800fb.png)

![image](https://user-images.githubusercontent.com/71384968/107143224-2848af00-6934-11eb-931d-11c72db16278.png)

![image](https://user-images.githubusercontent.com/71384968/107143234-3a2a5200-6934-11eb-81b9-f9a67a009ed7.png)

**Comment by ElTyranos** [comment]
Transferred to suggestion box
