### ISSUE TITLE
Urraca of León crown

### ISSUE THREAD

**Issue by ElTyranos** [ElTyranos/CommunityFlavorPack#81]
![image](https://user-images.githubusercontent.com/6755711/108996797-248c8a80-769f-11eb-87b8-2ad83669f57d.png)

**Comment by Willemoak** [comment]
This is another iteration of the cylidricall tall crown you're already familiar with from modelling the Crown of Lombardy. Urraca may be wearing it higher because of the headscarf, but it's the same concept.

**Comment by ElTyranos** [comment]
Transferred to suggestion box.
