### ISSUE TITLE
Commoner Cloak available with monk habits causing clipping

### ISSUE THREAD

**Issue by voy178** [ElTyranos/CommunityFlavorPack#91]
Ideally, the devoted would be an exception to the rule of wearing cloaks mainly because the habit is all they're supposed to wear anyways.

![20210320233509_1](https://user-images.githubusercontent.com/44323473/111887415-3844bb80-89d5-11eb-9a6a-8207909a34cb.jpg)

**Comment by ElTyranos** [comment]
Thank you! It will be fixed in next hotfix.
